### ISSUE TITLE
Add a command to enable a Travis build to sign & publish an extension

### ISSUE THREAD

**Issue by jessitron** [atomist/rug-rugs#68]
I want to publish my Elm language extension, from a Travis build.
Need a Rug to enable this please, for either a Rug language extension or a Rug function.

**Comment by russmiles** [comment]
![9e8e8061b8f73aa39ac3a9f2e7959d38](https://user-images.githubusercontent.com/104529/28024084-9f2dd2e4-6587-11e7-9c25-20b76ab713b5.jpg)

**Comment by jessitron** [comment]
@russmiles worked on a manual implementation of this process today. It was hard.
For later reference, here was our process: https://github.com/jessitron/kats-parser/compare/17db7d1...11f1b84

**Comment by jessitron** [comment]
checklist:
[ ] Copy these files from this repository:
    [ ] .travis.yml
    [ ] src/main/scripts/travis-build.bash
    [ ] settings.xml
[ ] Add to pom.xml:
    [ ] property <timestamp>${maven.build.timestamp}</timestamp>
    [ ] property <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
[ ] Enable the repository for builds on travis-ci.org

**Comment by jessitron** [comment]
signed-release profile: +     <profile>
+            <id>signedRelease</id>
+            <activation>
+                <activeByDefault>false</activeByDefault>
+            </activation>
+            <build>
+                <plugins>
+                    <plugin>
+                        <groupId>org.apache.maven.plugins</groupId>
+                        <artifactId>maven-gpg-plugin</artifactId>
+                        <version>1.6</version>
+                        <executions>
+                            <execution>
+                                <id>sign-artifacts</id>
+                                <phase>verify</phase>
+                                <goals>
+                                    <goal>sign</goal>
+                                </goals>
+                            </execution>
+                        </executions>
+                    </plugin>
+                </plugins>
+            </build>
+        </profile>

**Comment by jessitron** [comment]
distributionManagement repository public-atomist-release:
```
<distributionManagement>
        <repository>
            <id>public-atomist-release</id>
            <name>Atomist Release</name>
            <url>https://atomist.jfrog.io/atomist/libs-release-local</url>
        </repository>
    </distributionManagement>
```

**Comment by jessitron** [comment]
this is not going to be relevant in the future
